In [66]:
import pandas as pd 

PATHS = {
    'pop_2020': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/population_2020.CSV",
    'pop_2014': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/population_2014.xls",
    'diplo_2020': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/diplome_2020.CSV",
    'diplo_2014': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/diplome_2014.xls",
    'rev_2019': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/revenu_2019.csv",
    'rev_2013': "/Users/romain/Desktop/Projets DS/Python-project/analyse/data/revenu_2013.xls"
}

df_pop_2020 = pd.read_csv(PATHS['pop_2020'], sep=';',dtype={'COM':'str'})
df_pop_2014 = pd.read_excel(PATHS['pop_2014'],header=5,dtype={'COM':'str'})
df_diplo_2020 = pd.read_csv(PATHS['diplo_2020'], sep=';',header=0,dtype={'COM':'str'})
df_diplo_2014 = pd.read_excel(PATHS['diplo_2014'],header=5,dtype={'CODGEO':'str'})
df_rev_2019 = pd.read_csv(PATHS['rev_2019'], sep=';',dtype={'CODGEO':'str'})
df_rev_2013 = pd.read_excel(PATHS['rev_2013'],header=5,dtype={'CODGEO':'str'})

/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_75012/864678703.py:12: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pop_2020 = pd.read_csv(PATHS['pop_2020'], sep=';',dtype={'COM':'str'})
/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_75012/864678703.py:14: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_diplo_2020 = pd.read_csv(PATHS['diplo_2020'], sep=';',header=0,dtype={'COM':'str'})

Fusion en un unqiue .csv de toutes les données explicatives brutes (sans delta). On fera deltaY=delta vote, sur les deltaX.

In [93]:
print("Pop 2014 unique ?", df_pop_2014['COM'].is_unique)
print("Pop 2020 unique ?", df_pop_2020['COM'].is_unique)
print("Diplo 2020 unique ?", df_diplo_2020['COM'].is_unique)
print("Diplo 2014 unique ?", df_diplo_2014['CODGEO'].is_unique)
print("Rev 2013 unique ?", df_rev_2013['CODGEO'].is_unique)
print("Rev 2019 unique ?", df_rev_2019['CODGEO'].is_unique)

Pop 2014 unique ? False
Pop 2020 unique ? False
Diplo 2020 unique ? False
Diplo 2014 unique ? True
Rev 2013 unique ? True
Rev 2019 unique ? True

In [67]:

df_pop_2020=df_pop_2020[['COM','P20_POP','C20_POP15P_CS3']]
df_pop_2014=df_pop_2014[['COM','P14_POP','C14_POP15P_CS3']]
df_pop_2020.head()
df_pop_2014.head()
df_diplo_2014=df_diplo_2014[['CODGEO','P14_NSCOL15P_SUP']]
df_diplo_2020=df_diplo_2020[['COM','P20_NSCOL15P_SUP2','P20_NSCOL15P_SUP34','P20_NSCOL15P_SUP5']]
df_rev_2013=df_rev_2013[['CODGEO','MED13']]
df_rev_2019=df_rev_2019[['CODGEO','MED19']]

In [46]:
df_diplo_2014.head()

  CODGEO  P14_NSCOL15P_SUP
0  01001        141.000000
1  01002         59.995885
2  01004       2326.327150
3  01005        281.383570
4  01006         12.881818

In [68]:
df=pd.merge(df_pop_2014,df_diplo_2014, left_on='COM', right_on='CODGEO', how='left')

In [70]:
df.head()
df.drop(columns=['CODGEO'])
#df_rev_2013.head()

         COM      P14_POP  C14_POP15P_CS3  P14_NSCOL15P_SUP
0      01001   767.000000       75.000000        141.000000
1      01002   239.000000       14.753086         59.995885
2      01004  1727.477146       48.224303       2326.327150
3      01004  3732.314172      116.808002       2326.327150
4      01004  3915.910166      207.505223       2326.327150
...      ...          ...             ...               ...
50089  97424  1541.337506       28.353898        215.884637
50090  97424  1714.268397        3.963154        215.884637
50091  97424   674.834098        0.000000        215.884637
50092  97424   951.476366        0.000000        215.884637
50093  97424   413.083632        0.000000        215.884637

[50094 rows x 4 columns]

In [ ]:

df_2014=pd.merge(df,df_rev_2013, left_on='COM', right_on='CODGEO', how='left')

,COM,P14_POP,C14_POP15P_CS3,CODGEO_x,P14_NSCOL15P_SUP,CODGEO_y,MED13
0,01001,767.000000,75.000000,01001,141.000000,01001,22130.0
1,01002,239.000000,14.753086,01002,59.995885,01002,23213.0
2,01004,1727.477146,48.224303,01004,2326.327150,01004,19554.0
3,01004,3732.314172,116.808002,01004,2326.327150,01004,19554.0
4,01004,3915.910166,207.505223,01004,2326.327150,01004,19554.0

In [73]:
df_2014=df_2014.drop(columns=['CODGEO_x','CODGEO_y'])

In [74]:
df_2014.head()

     COM      P14_POP  C14_POP15P_CS3  P14_NSCOL15P_SUP    MED13
0  01001   767.000000       75.000000        141.000000  22130.0
1  01002   239.000000       14.753086         59.995885  23213.0
2  01004  1727.477146       48.224303       2326.327150  19554.0
3  01004  3732.314172      116.808002       2326.327150  19554.0
4  01004  3915.910166      207.505223       2326.327150  19554.0

In [77]:
df_rev_2019.head()

  CODGEO  MED19
0  01001  23970
1  01002  23640
2  01004  20510
3  01005  24050
4  01006      s

In [75]:
df_2020=pd.merge(df_pop_2020,df_diplo_2020, left_on='COM', right_on='COM', how='left')

In [78]:
df_2020.head()
df_2020=pd.merge(df_2020,df_rev_2019, left_on='COM', right_on='CODGEO', how='left')

In [80]:
df_2020.head()
df_2020=df_2020.drop(columns=['CODGEO'])

In [81]:
df_2020.head()

,COM,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,806.00000,61.774238,83.435537,58.938581,38.706320,23970
1,01002,262.00000,18.283656,28.977294,27.590460,23.934686,23640
2,01004,1805.37661,88.925752,165.494318,86.425855,92.586354,20510
3,01004,1805.37661,88.925752,289.813096,157.410750,144.206181,20510
4,01004,1805.37661,88.925752,354.597339,264.855653,166.585701,20510

In [82]:
df=pd.merge(df_2014,df_2020, left_on='COM', right_on='COM', how='left')

In [88]:
df.head(100)

,COM,P14_POP,C14_POP15P_CS3,P14_NSCOL15P_SUP,MED13,P20_POP,C20_POP15P_CS3,P20_NSCOL15P_SUP2,P20_NSCOL15P_SUP34,P20_NSCOL15P_SUP5,MED19
0,01001,767.000000,75.000000,141.000000,22130.000000,806.000000,61.774238,83.435537,58.938581,38.706320,23970
1,01002,239.000000,14.753086,59.995885,23213.000000,262.000000,18.283656,28.977294,27.590460,23.934686,23640
2,01004,1727.477146,48.224303,2326.327150,19554.000000,1805.376610,88.925752,165.494318,86.425855,92.586354,20510
3,01004,1727.477146,48.224303,2326.327150,19554.000000,1805.376610,88.925752,289.813096,157.410750,144.206181,20510
4,01004,1727.477146,48.224303,2326.327150,19554.000000,1805.376610,88.925752,354.597339,264.855653,166.585701,20510
...,...,...,...,...,...,...,...,...,...,...,...
95,01033,1291.253020,46.099187,1792.776546,19063.913043,2911.675989,131.772046,145.663242,141.539818,96.061711,22440
96,01033,1291.253020,46.099187,1792.776546,19063.913043,2911.675989,131.772046,85.690318,34.404942,53.015852,22440
97,01033,1291.253020,46.099187,1792.776546,19063.913043,2911.675989,131.772046,362.898219,247.616540,182.376749,22440
98,01033,1291.253020,46.099187,1792.776546,19063.913043,2381.302013,120.817175,225.411824,110.972251,209.871891,22440
99,01033,1291.253020,46.099187,1792.776546,19063.913043,2381.302013,120.817175,213.277092,126.427706,123.501527,22440

In [86]:
df_pop_2014.head(50)

      COM      P14_POP  C14_POP15P_CS3
0   01001   767.000000       75.000000
1   01002   239.000000       14.753086
2   01004  1727.477146       48.224303
3   01004  3732.314172      116.808002
4   01004  3915.910166      207.505223
5   01004  4646.298516      370.750951
6   01005  1627.000000      105.518839
7   01006   109.000000        4.954545
8   01007  2570.000000      195.000000
9   01008   743.000000       71.903226
10  01009   338.000000       16.047478
11  01010  1142.000000       42.731525
12  01011   397.000000       70.119481
13  01012   325.000000       33.440514
14  01013   157.000000        7.850000
15  01014  3405.000000      153.502860
16  01015   638.000000       24.399073
17  01016   440.000000       19.426049
18  01017   427.000000        4.874429
19  01019    23.000000        0.000000
20  01021  1376.000000       99.237497
21  01022  1193.000000       30.253051
22  01023    66.000000        5.000000
23  01024  3386.000000      152.424437
24  01025  3177.000000      115.000000
25  01026   881.000000       20.000000
26  01027  2973.000000      237.421691
27  01028   585.000000       24.497487
28  01029   678.000000       36.183454
29  01030   886.000000       45.000000
30  01031  3656.000000      165.392208
31  01032  3296.000000      207.328446
32  01033  1291.253020       46.099187
33  01033  3046.446810      183.146856
34  01033  2695.739752      152.695152
35  01033  2742.836154       97.732643
36  01033  1968.724264       72.452861
37  01034  3085.708773      137.269341
38  01034  3580.438427      157.064314
39  01034  2316.852799       44.122288
40  01035   321.000000       10.190476
41  01036   549.000000       23.028523
42  01037   282.000000        9.633791
43  01038   731.000000       43.169291
44  01039   467.000000       12.262582
45  01040   477.000000        9.855372
46  01041   749.000000       44.176944
47  01042   265.000000       28.804348
48  01043  4541.000000      535.000000
49  01044   595.000000       37.058824

Fusion en un unqiue .csv de toutes les données explicatives brutes (sans delta). On fera deltaY=delta vote, sur les deltaX.